apiVersion: v2
name: argocd
description: A Helm chart for Argo CD
type: application
version: 5.51.2
appVersion: "2.8.4"
dependencies:
- name: argo-cd
  version: 5.51.2
  repository: https://argoproj.github.io/argo-helm
