apiVersion: v2
name: argo-rollouts
description: A Helm chart for Argo Rollouts
type: application
version: 2.40.4
appVersion: "v1.6.4"
dependencies:
- name: argo-rollouts
  version: 2.40.4
  repository: https://argoproj.github.io/argo-helm
