# Default values for prometheus.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

prometheus:
  namespace: prometheus

  # Scrape all namespaces
  prometheusSpec:
    serviceMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelector: {}
    podMonitorSelectorNilUsesHelmValues: false
    podMonitorSelector: {}
    ruleSelectorNilUsesHelmValues: false
    ruleSelector: {}
